### ISSUE TITLE
importers/markdown_awesome: don't split long lines in YAML output

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#103]
https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/flagsmith.yml

Current:

```yaml
description: Flagsmith provides a dashboard, API and SDKs for adding Feature Flags
  to your applications. Alternative to LaunchDarkly.
```

Expected:

```yaml
description: Flagsmith provides a dashboard, API and SDKs for adding Feature Flags to your applications. Alternative to LaunchDarkly.
```

**Comment by nodiscc** [comment]
The problem is only reproducible when hecat runs through github actions. When run locally, no line wrapping occurs:

```bash
$ make clone_awesome_selfhosted test_import_awesome_selfhosted && cat awesome-selfhosted-data/software/flagsmith.yml
```
```yaml
name: Flagsmith
website_url: https://flagsmith.com
description: Flagsmith provides a dashboard, API and SDKs for adding Feature Flags to your applications. Alternative to LaunchDarkly.
licenses:
  - BSD-3-Clause
platforms:
  - Docker
tags:
  - Miscellaneous
source_code_url: https://github.com/flagsmith/flagsmith

```
