### ISSUE TITLE
importers/shaarli_api: sort keys in each dict, in a sensible order

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#50]
Make raw data more readable by ordering keys by "usefulness" for a human reader
- title
- url
- id
- private
- shorturl
- created
- updated
- tags
- description

```yaml
- created: '2022-07-27T22:56:06+02:00'
  description: ''
  id: 6624
  private: false
  shorturl: zKVXxA
  tags:
  - video
  - vj
  - math
  - nodl
  title: The Burning Ship - A Fractal Zoom (5e598) (4k 60fps) - YouTube
  updated: '2022-07-29T14:15:39+02:00'
  url: https://www.youtube.com/watch?v=2S3lc2G3rWs
```

->

```yaml
- title: The Burning Ship - A Fractal Zoom (5e598) (4k 60fps) - YouTube
  url: https://www.youtube.com/watch?v=2S3lc2G3rWs
  id: 6624
  private: false
  shorturl: zKVXxA
  created: '2022-07-27T22:56:06+02:00'
  updated: '2022-07-29T14:15:39+02:00'
  tags:
  - video
  - vj
  - math
  - nodl
  description: ''
```
