### ISSUE TITLE
importers/markown_awesome: add ability to import from the awesome-selfhosted/non-free.md format

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#57]
- https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3198

Example usage:

```yaml
  - name: import data from awesome-selfhosted non-free.md
    module: importers/markdown_awesome
    module_options:
      source_file: awesome-selfhosted/non-free.md
      output_directory: awesome-selfhosted-data
```

- [x] `⊘ Proprietary` tag position could be adjusted directly in the source file beforehand to make the import easier
- [x] If so, https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md must be updated
- [x] exporters/markdown_singlepage: do not render items with non-free licenses in the main output file, render them in a separate file `non-free.md`
