### ISSUE TITLE
importer: import 'delegate' (Please visit), 'related_tags' (Related:) and section descriptions from markdown

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#6]

**Comment by nodiscc** [comment]
Input:

```markdown
...
- [µTask](https://github.com/ovh/utask) - µTask is an automation engine that models and executes business processes declared in yaml. `BSD-3-Clause` `Go`

### Blogging Platforms

**[`^        back to top        ^`](#)**

A [blog](https://en.wikipedia.org/wiki/Blog) is a discussion or informational website published on the World Wide Web consisting of discrete, often informal diary-style text entries (posts).

_Related: [Static Site Generators](#static-site-generators), [Content Management Systems](#content-management-systems-cms)_

_See also: [WeblogMatrix](https://www.weblogmatrix.org/)_

- [Antville](https://antville.org) - Free, open source project aimed at the development of a high performance, feature rich weblog hosting software. ([Source Code](https://github.com/antville/antville)) `Apache-2.0` `Javascript`
```

Expected output:

```yaml
# tags/Blogging Platforms.yml
...
description: 'A [blog](https://en.wikipedia.org/wiki/Blog) is a discussion or informational website published on the World Wide Web consisting of discrete, often informal diary-style text entries (posts).'
related_tags:
  - 'Static Site Generators'
  - 'Content Management Systems'
```

external_links:
  - title: 'Static Site Generators'
    url: https://www.weblogmatrix.org/
