### ISSUE TITLE
exporters/html_table: line breaks inside code blocks are not redenered (markdown)

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#83]
Input:
```yaml
- created: '2020-07-23T19:54:15+02:00'
  description: "```\r\n   rescue:\r\n     - debug:\r\n         msg: 'I caught an error, can do stuff here to fix it, :-)'\r\n   always:\r\n     - debug:\r\n         msg: \"This always executes, :-)\"\r\n```"
  id: 232
  private: false
  shorturl: oJmZFg
  tags:
  - doc
  - admin
  - ansible
  title: Blocks — Ansible Documentation
  updated: '2023-01-25T15:02:16+01:00'
  url: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html
```

Output:

```html
<tr>
  <td><a href='https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html'>Blocks — Ansible Documentation</a>
  <br/><details><summary></summary><p><code>rescue:
     - debug:
         msg: 'I caught an error, can do stuff here to fix it, :-)'
   always:
     - debug:
         msg: "This always executes, :-)"</code></p></details>
  </td>
  <td><code>@doc</code> <code>@admin</code> <code>@ansible</code></td>
<tr/>
```

Rendered:

![image](https://user-images.githubusercontent.com/3950390/216793101-9dafa98e-f8b7-4aac-9fbb-06806094ff82.png)
