### ISSUE TITLE
exporters/html_table: markdown blockquotes are not rendered

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#86]
Input:
```yaml
- created: '2017-07-13T03:05:20+02:00'
  description: '&gt;    That gibberish he talked was Cityspeak, gutter talk, a mishmash of Japanese, Spanish, German, what have you. I didn’t really need a translator. I knew the lingo, every good cop did. But I wasn’t going to make it easier for him.'
  id: 2083
  private: false
  shorturl: Bl8mkA
  tags:
  - games
  - cyberpunk
  title: 'Cityspeak | Off-world: The Blade Runner Wiki | FANDOM powered by Wikia'
  updated: '2022-11-11T15:13:56+01:00'
  url: http://bladerunner.wikia.com/wiki/Cityspeak
```

Output:

```html
<tr>
  <td><a href='http://bladerunner.wikia.com/wiki/Cityspeak'>Cityspeak | Off-world: The Blade Runner Wiki | FANDOM powered by Wikia</a>
  <br/><details><summary></summary><p>&gt;    That gibberish he talked was Cityspeak, gutter talk, a mishmash of Japanese, Spanish, German, what have you. I didn’t really need a translator. I knew the lingo, every good cop did. But I wasn’t going to make it easier for him.</p></details>
  </td>
  <td><code>@games</code> <code>@cyberpunk</code></td>
<tr/>
```

Rendered:

![image](https://user-images.githubusercontent.com/3950390/216793238-884d2507-285c-4434-a56f-83fe509b792b.png)

**Comment by nodiscc** [comment]
Not a bug, `&gt;` in source data will not be interpreted as a blockquote start, but `>` will

Input:

```json
    {
        "created": "2022-12-18T17:39:13+01:00",
        "description": "> For people who just can't get enough of that warm vintage sound! Post, discuss, and learn about the excellent audio gear of past generations.",
        "id": 7014,
        "private": false,
        "shorturl": "QkwHfA",
        "tags": [
            "forums",
            "av",
            "technology"
        ],
        "title": "/r/Vintage Audio",
        "updated": "2022-12-21T10:44:42+01:00",
        "url": "https://old.reddit.com/r/vintageaudio/"
    },
```

Output:

```yaml
- created: '2022-12-18T17:39:13+01:00'
  description: "> For people who just can't get enough of that warm vintage sound! Post, discuss, and learn about the excellent audio gear of past generations."
  id: 7014
  private: false
  shorturl: QkwHfA
  tags:
  - forums
  - av
  - technology
  title: /r/Vintage Audio
  updated: '2022-12-21T10:44:42+01:00'
  url: https://old.reddit.com/r/vintageaudio/
```

Rendered:

![image](https://user-images.githubusercontent.com/3950390/217843882-9cb06a9d-726f-4ed7-926d-81acbeba1154.png)
