### ISSUE TITLE
importers/shaarli_api: allow fetching shaarli data from the API directly (no external call to shaarli-client)

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#93]
```yaml
module_options:
  shaarli_api_url = https://shaarli.example.org # shaarli instance URL
  shaarli_api_secret = CHANGEME # API secret
  shaarli_api_insecure: False # (default False) bypass API SSL/TLS certificate verification
  shaarli_api_visibility: all # (all/public/private, default all) only get shaares with this visibility status
  source_file: shaarli-export.json # JSON file to store shaarli API response to
```
